#ifndef CALCLIBRARY_GLOBAL_H
#define CALCLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CALCLIBRARY_LIBRARY)
#  define CALCLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CALCLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CALCLIBRARY_GLOBAL_H
