#ifndef SETTINGSLIBRARY_GLOBAL_H
#define SETTINGSLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SETTINGSLIBRARY_LIBRARY)
#  define SETTINGSLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SETTINGSLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SETTINGSLIBRARY_GLOBAL_H
